//go:build imagick && !vips && cgo

package image

import "golang.org/x/exp/maps"

var imageFormatDescription = map[string]string{
	"3FR":    "Hasselblad CFV/H3D39II Raw Format",
	"3G2":    "Media Container",
	"3GP":    "Media Container",
	"A":      "Raw alpha samples",
	"AAI":    "AAI Dune image",
	"AI":     "Adobe Illustrator CS2",
	"APNG":   "Animated Portable Network Graphics",
	"ART":    "PFS: 1st Publisher Clip Art",
	"ARW":    "Sony Alpha Raw Format",
	"ASHLAR": "Image sequence laid out in continuous irregular courses",
	"AVI":    "Microsoft Audio/Visual Interleaved",
	"AVIF":   "AV1 Image File Format (1.12.0)",
	"AVS":    "AVS X image",
	"B":      "Raw blue samples",
	"BAYER":  "Raw mosaiced samples",
	"BAYERA": "Raw mosaiced and alpha samples",
	"BGR":    "Raw blue, green, and red samples",
	"BGRA":   "Raw blue, green, red, and alpha samples",
	"BGRO":   "Raw blue, green, red, and opacity samples",
	"BIE":    "Joint Bi-level Image experts Group interchange format (2.1)",
	"BMP":    "Microsoft Windows bitmap image",
	"BMP2":   "Microsoft Windows bitmap image (V2)",
	"BMP3":   "Microsoft Windows bitmap image (V3)",
	"BRF":    "BRF ASCII Braille format",
	"C":      "Raw cyan samples",
	"CAL":    "Continuous Acquisition and Life-cycle Support Type 1",

	"CALS": "Continuous Acquisition and Life-cycle Support Type 1",

	"CANVAS":  "Constant image uniform color",
	"CAPTION": "Caption",
	"CIN":     "Cineon Image File",
	"CIP":     "Cisco IP phone image format",
	"CLIP":    "Image Clip Mask",
	"CMYK":    "Raw cyan, magenta, yellow, and black samples",
	"CMYKA":   "Raw cyan, magenta, yellow, black, and alpha samples",
	"CR2":     "Canon Digital Camera Raw Format",
	"CR3":     "Canon Digital Camera Raw Format",
	"CRW":     "Canon Digital Camera Raw Format",
	"CUBE":    "Cube LUT",
	"CUR":     "Microsoft icon",
	"CUT":     "DR Halo",
	"DATA":    "Base64-encoded inline images",
	"DCM":     "Digital Imaging and Communications in Medicine image",

	"DCR":   "Kodak Digital Camera Raw Format",
	"DCRAW": "Raw Photo Decoder (dcraw)",
	"DCX":   "ZSoft IBM PC multi-page Paintbrush",
	"DDS":   "Microsoft DirectDraw Surface",
	"DFONT": "Multi-face font package (Freetype 2.11.1)",
	"DJVU":  "Deja vu",

	"DNG": "Digital Negative Raw Format",
	"DPX": "SMPTE 268M-2003 (DPX 2.0)",

	"DXT1":     "Microsoft DirectDraw Surface",
	"DXT5":     "Microsoft DirectDraw Surface",
	"EPDF":     "Encapsulated Portable Document Format",
	"EPI":      "Encapsulated PostScript Interchange format",
	"EPS":      "Encapsulated PostScript",
	"EPS2":     "Level II Encapsulated PostScript",
	"EPS3":     "Level III Encapsulated PostScript",
	"EPSF":     "Encapsulated PostScript",
	"EPSI":     "Encapsulated PostScript Interchange format",
	"EPT":      "Encapsulated PostScript with TIFF preview",
	"EPT2":     "Encapsulated PostScript Level II with TIFF preview",
	"EPT3":     "Encapsulated PostScript Level III with TIFF preview",
	"ERF":      "Epson Raw Format",
	"EXR":      "High Dynamic-range (HDR) (OpenEXR 2.5.7)",
	"FARBFELD": "Farbfeld",
	"FAX":      "Group 3 FAX",

	"FF":       "Farbfeld",
	"FFF":      "Hasselblad CFV/H3D39II Raw Format",
	"FILE":     "Uniform Resource Locator (file://)",
	"FITS":     "Flexible Image Transport System",
	"FL32":     "FilmLight",
	"FLV":      "Flash Video Stream",
	"FRACTAL":  "Plasma fractal image",
	"FTP":      "Uniform Resource Locator (ftp://)",
	"FTS":      "Flexible Image Transport System",
	"FTXT":     "Formatted text image",
	"G":        "Raw green samples",
	"G3":       "Group 3 FAX",
	"G4":       "Group 4 FAX",
	"GIF":      "CompuServe graphics interchange format",
	"GIF87":    "CompuServe graphics interchange format (version 87a)",
	"GRADIENT": "Gradual linear passing from one shade to another",
	"GRAY":     "Raw gray samples",
	"GRAYA":    "Raw gray and alpha samples",
	"GROUP4":   "Raw CCITT Group4",

	"HALD":      "Identity Hald color lookup table image",
	"HDR":       "Radiance RGBE image format",
	"HEIC":      "High Efficiency Image Format (1.12.0)",
	"HEIF":      "High Efficiency Image Format (1.12.0)",
	"HISTOGRAM": "Histogram of the image",
	"HRZ":       "Slow Scan TeleVision",
	"HTM":       "Hypertext Markup Language and a client-side image map",
	"HTML":      "Hypertext Markup Language and a client-side image map",
	"HTTP":      "Uniform Resource Locator (http://)",
	"HTTPS":     "Uniform Resource Locator (https://)",
	"ICB":       "Truevision Targa image",
	"ICO":       "Microsoft icon",
	"ICON":      "Microsoft icon",
	"IIQ":       "Phase One Raw Format",
	"INFO":      "The image format and characteristics",
	"INLINE":    "Base64-encoded inline images",
	"IPL":       "IPL Image Sequence",
	"ISOBRL":    "ISO/TR 11548-1 format",
	"ISOBRL6":   "ISO/TR 11548-1 format 6dot",
	"J2C":       "JPEG-2000 Code Stream Syntax (2.4.0)",
	"J2K":       "JPEG-2000 Code Stream Syntax (2.4.0)",
	"JBG":       "Joint Bi-level Image experts Group interchange format (2.1)",
	"JBIG":      "Joint Bi-level Image experts Group interchange format (2.1)",
	"JNG":       "JPEG Network Graphics",

	"JNX":   "Garmin tile format",
	"JP2":   "JPEG-2000 File Format Syntax (2.4.0)",
	"JPC":   "JPEG-2000 Code Stream Syntax (2.4.0)",
	"JPE":   "Joint Photographic Experts Group JFIF format (libjpeg-turbo 2.1.2)",
	"JPEG":  "Joint Photographic Experts Group JFIF format (libjpeg-turbo 2.1.2)",
	"JPG":   "Joint Photographic Experts Group JFIF format (libjpeg-turbo 2.1.2)",
	"JPM":   "JPEG-2000 File Format Syntax (2.4.0)",
	"JPS":   "Joint Photographic Experts Group JFIF format (libjpeg-turbo 2.1.2)",
	"JPT":   "JPEG-2000 File Format Syntax (2.4.0)",
	"JSON":  "The image format and characteristics",
	"K":     "Raw black samples",
	"K25":   "Kodak Digital Camera Raw Format",
	"KDC":   "Kodak Digital Camera Raw Format",
	"LABEL": "Image label",
	"M":     "Raw magenta samples",
	"M2V":   "MPEG Video Stream",
	"M4V":   "Raw VIDEO-4 Video",
	"MAC":   "MAC Paint",
	"MAP":   "Colormap intensities and indices",
	"MASK":  "Image Clip Mask",
	"MAT":   "MATLAB level 5 image format",
	"MATTE": "MATTE format",
	"MDC":   "Minolta Digital Camera Raw Format",
	"MEF":   "Mamiya Raw Format",
	"MIFF":  "Magick Image File Format",
	"MKV":   "Multimedia Container",
	"MNG":   "Multiple-image Network Graphics (libpng 1.6.37)",

	"MONO":    "Raw bi-level bitmap",
	"MOS":     "Aptus Leaf Raw Format",
	"MOV":     "MPEG Video Stream",
	"MP4":     "VIDEO-4 Video Stream",
	"MPC":     "Magick Pixel Cache image format",
	"MPEG":    "MPEG Video Stream",
	"MPG":     "MPEG Video Stream",
	"MPO":     "Joint Photographic Experts Group JFIF format (libjpeg-turbo 2.1.2)",
	"MRW":     "Sony (Minolta) Raw Format",
	"MSL":     "Magick Scripting Language",
	"MSVG":    "ImageMagick's own SVG internal renderer",
	"MTV":     "MTV Raytracing image format",
	"MVG":     "Magick Vector Graphics",
	"NEF":     "Nikon Digital SLR Camera Raw Format",
	"NRW":     "Nikon Digital SLR Camera Raw Format",
	"NULL":    "Constant image of uniform color",
	"O":       "Raw opacity samples",
	"ORA":     "OpenRaster format",
	"ORF":     "Olympus Digital Camera Raw Format",
	"OTB":     "On-the-air bitmap",
	"OTF":     "Open Type font (Freetype 2.11.1)",
	"PAL":     "16bit/pixel interleaved YUV",
	"PALM":    "Palm pixmap",
	"PAM":     "Common 2-dimensional bitmap format",
	"PANGO":   "Pango Markup Language (Pangocairo 1.50.6)",
	"PATTERN": "Predefined pattern",
	"PBM":     "Portable bitmap format (black and white)",
	"PCD":     "Photo CD",
	"PCDS":    "Photo CD",
	"PCL":     "Printer Control Language",
	"PCT":     "Apple Macintosh QuickDraw/PICT",
	"PCX":     "ZSoft IBM PC Paintbrush",
	"PDB":     "Palm Database ImageViewer Format",
	"PDF":     "Portable Document Format",
	"PDFA":    "Portable Document Archive Format",
	"PEF":     "Pentax Electronic Raw Format",
	"PES":     "Embrid Embroidery Format",
	"PFA":     "Postscript Type 1 font (ASCII) (Freetype 2.11.1)",
	"PFB":     "Postscript Type 1 font (binary) (Freetype 2.11.1)",
	"PFM":     "Portable float format",
	"PGM":     "Portable graymap format (gray scale)",
	"PGX":     "JPEG 2000 uncompressed format",
	"PHM":     "Portable half float format",
	"PICON":   "Personal Icon",
	"PICT":    "Apple Macintosh QuickDraw/PICT",
	"PIX":     "Alias/Wavefront RLE image format",
	"PJPEG":   "Joint Photographic Experts Group JFIF format (libjpeg-turbo 2.1.2)",
	"PLASMA":  "Plasma fractal image",
	"PNG":     "Portable Network Graphics (libpng 1.6.37)",

	"PNG00":     "PNG inheriting bit-depth, color-type from original, if possible",
	"PNG24":     "opaque or binary transparent 24-bit RGB",
	"PNG32":     "opaque or transparent 32-bit RGBA",
	"PNG48":     "opaque or binary transparent 48-bit RGB",
	"PNG64":     "opaque or transparent 64-bit RGBA",
	"PNG8":      "8-bit indexed with optional binary transparency",
	"PNM":       "Portable anymap",
	"POCKETMOD": "Pocketmod Personal Organizer",
	"PPM":       "Portable pixmap format (color)",
	"PS":        "PostScript",
	"PS2":       "Level II PostScript",
	"PS3":       "Level III PostScript",
	"PSB":       "Adobe Large Document Format",
	"PSD":       "Adobe Photoshop bitmap",
	"PTIF":      "Pyramid encoded TIFF",

	"PWP":        "Seattle Film Works",
	"QOI":        "Quite OK image format",
	"R":          "Raw red samples",
	"RADIAL-GRA": "r--   Gradual radial passing from one shade to another",
	"RAF":        "Fuji CCD-RAW Graphic Raw Format",
	"RAS":        "SUN Rasterfile",
	"RAW":        "Raw",
	"RGB":        "Raw red, green, and blue samples",
	"RGB565":     "Raw red, green, blue samples in 565 format",
	"RGBA":       "Raw red, green, blue, and alpha samples",
	"RGBO":       "Raw red, green, blue, and opacity samples",
	"RGF":        "LEGO Mindstorms EV3 Robot Graphic Format (black and white)",
	"RLA":        "Alias/Wavefront image",
	"RLE":        "Utah Run length encoded image",
	"RMF":        "Raw Media Format",
	"RW2":        "Panasonic Lumix Raw Format",
	"RWL":        "Leica Raw Format",
	"SCR":        "ZX-Spectrum SCREEN$",
	"SCREENSHOT": "Screen shot",
	"SCT":        "Scitex HandShake",
	"SFW":        "Seattle Film Works",
	"SGI":        "Irix RGB image",
	"SHTML":      "Hypertext Markup Language and a client-side image map",
	"SIX":        "DEC SIXEL Graphics Format",
	"SIXEL":      "DEC SIXEL Graphics Format",
	"SPARSE-COL": "Sparse Color",
	"SR2":        "Sony Raw Format 2",
	"SRF":        "Sony Raw Format",
	"SRW":        "Samsung Raw Format",
	"STEGANO":    "Steganographic image",
	"STI":        "Sinar CaptureShop Raw Format",
	"STRIMG":     "String to image and back",
	"SUN":        "SUN Rasterfile",
	"SVG":        "Scalable Vector Graphics (XML 2.9.13)",
	"SVGZ":       "Compressed Scalable Vector Graphics (XML 2.9.13)",
	"TEXT":       "Text",
	"TGA":        "Truevision Targa image",
	"THUMBNAIL":  "EXIF Profile Thumbnail",
	"TIFF":       "Tagged Image File Format (LIBTIFF, Version 4.3.0)",

	"TIFF64": "Tagged Image File Format (64-bit) (LIBTIFF, Version 4.3.0)",

	"TILE":   "Tile image with a texture",
	"TIM":    "PSX TIM",
	"TM2":    "PS2 TIM2",
	"TTC":    "TrueType font collection (Freetype 2.11.1)",
	"TTF":    "TrueType font (Freetype 2.11.1)",
	"TXT":    "Text",
	"UBRL":   "Unicode Text format",
	"UBRL6":  "Unicode Text format 6dot",
	"UIL":    "X-Motif UIL table",
	"UYVY":   "16bit/pixel interleaved YUV",
	"VDA":    "Truevision Targa image",
	"VICAR":  "Video Image Communication And Retrieval",
	"VID":    "Visual Image Directory",
	"VIFF":   "Khoros Visualization image",
	"VIPS":   "VIPS image",
	"VST":    "Truevision Targa image",
	"WBMP":   "Wireless Bitmap (level 0) image",
	"WEBM":   "Open Web Media",
	"WEBP":   "WebP Image Format (libwebp 1.2.2 [020F])",
	"WMV":    "Windows Media Video",
	"WPG":    "Word Perfect Graphics",
	"X":      "X Image",
	"X3F":    "Sigma Camera RAW Format",
	"XBM":    "X Windows system bitmap (black and white)",
	"XC":     "Constant image uniform color",
	"XCF":    "GIMP image",
	"XPM":    "X Windows system pixmap (color)",
	"XPS":    "Microsoft XML Paper Specification",
	"XV":     "Khoros Visualization image",
	"XWD":    "X Windows system window dump (color)",
	"Y":      "Raw yellow samples",
	"YAML":   "The image format and characteristics",
	"YCBCR":  "Raw Y, Cb, and Cr samples",
	"YCBCRA": "Raw Y, Cb, Cr, and alpha samples",
	"YUV":    "CCIR 601 4:1:1 or 4:2:2",
}

var imageFormats = maps.Keys(imageFormatDescription)
