#localaddr = ":7685"
localaddr = ":0"
#domains = ["ubmedia", "mediathek"]
domains = ["ubmedia"]
instance = "ubimage"
resolveraddr = "127.0.0.1:7777"
resolvertimeout = "10m"
resolvernotfoundtimeout = "10s"
dbconn = "%%DATABASE_URL%%"
concurrency = 3

[server]
type = "minivault"
initialtimeout = "1h"
[server.minivault]
baseurl = "https://localhost:8759/api/v1"
parenttoken = "pa.2dc2553ea702db53.8c7d17de83f18739" #pa.2dc483e73851c137.15d94e61e0b377f1
tokentype = "server_cert"
tokenpolicies = ["instance_ubimage.mediaserveraction"]
tokeninterval = "1h"
tokenttl = "2h"
certtype = "server_cert"
dnss = ["instance_ubimage.mediaserverproto.Action"]
uris = []
ips = []
certinterval = "8m"
certttl = "10m"
ca = ["""-----BEGIN CERTIFICATE-----
MIICxTCCAkqgAwIBAgIGAY4FTF/mMAoGCCqGSM49BAMDMIGYMQswCQYDVQQGEwJD
SDETMBEGA1UECBMKQmFzZWwgQ2l0eTEOMAwGA1UEBxMFQmFzZWwxIDAeBgNVBAkM
F1NjaMO2bmJlaW5zdHJhc3NlIDE4LTIwMQ0wCwYDVQQREwQ0MDU2MSEwHwYDVQQK
ExhVbml2ZXJzaXR5IExpYnJhcnkgQmFzZWwxEDAOBgNVBAMTB0R1bW15Q0EwHhcN
MjQwMzAzMTcxMTE1WhcNMzQwMzAxMTcxMTE1WjCBmDELMAkGA1UEBhMCQ0gxEzAR
BgNVBAgTCkJhc2VsIENpdHkxDjAMBgNVBAcTBUJhc2VsMSAwHgYDVQQJDBdTY2jD
tm5iZWluc3RyYXNzZSAxOC0yMDENMAsGA1UEERMENDA1NjEhMB8GA1UEChMYVW5p
dmVyc2l0eSBMaWJyYXJ5IEJhc2VsMRAwDgYDVQQDEwdEdW1teUNBMHYwEAYHKoZI
zj0CAQYFK4EEACIDYgAErHxZYoHwHzTqRg14Ve9/APs/D+sMSKDTpPTZYFocZedF
VGJEkeaCqQvsCY5G9WaHXI7jZtewKo/bHM/WcmXZB+cZNmJn/IyBHJAYh5xN5WBY
vUPJfRfQosSFr8SDE4MPo2EwXzAOBgNVHQ8BAf8EBAMCAoQwHQYDVR0lBBYwFAYI
KwYBBQUHAwIGCCsGAQUFBwMBMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFH+I
PuzNyAOrQ+rMTtywGqm3Z5ARMAoGCCqGSM49BAMDA2kAMGYCMQDJNau3j1v1FQHQ
n7kn+gEATGOm+9fBsgUCGXmKvLZPIJI3NI2URLmlmASdEIrg/N4CMQCNQio9BHom
JYLotIXmdUEmKuXZeKoc0eR1jA7kWdJNOvEpE73mx/zutDeNl3hRVP0=
-----END CERTIFICATE-----
"""]
usesystempool = false

[client]
type = "minivault"
initialtimeout = "1h"
[client.minivault]
baseurl = "https://localhost:8759/api/v1"
parenttoken = "pa.2dc2553ea702db53.8c7d17de83f18739" #pa.2dc483e73851c137.15d94e61e0b377f1
tokentype = "client_cert"
tokenpolicies = ["instance_ubimage.mediaserveraction"]
tokeninterval = "1h"
tokenttl = "2h"
certtype = "client_cert"
dnss = []
uris = [
    "grpc:miniresolverproto.MiniResolver",
    "grpc:ubmedia.mediaserverproto.Database",
    "grpc:mediathek.mediaserverproto.Database",
    "grpc:ubmedia.mediaserverproto.ActionDispatcher",
    "grpc:mediathek.mediaserverproto.ActionDispatcher"]
ips = []
certinterval = "8m"
certttl = "10m"
ca = ["""-----BEGIN CERTIFICATE-----
MIICxTCCAkqgAwIBAgIGAY4FTF/mMAoGCCqGSM49BAMDMIGYMQswCQYDVQQGEwJD
SDETMBEGA1UECBMKQmFzZWwgQ2l0eTEOMAwGA1UEBxMFQmFzZWwxIDAeBgNVBAkM
F1NjaMO2bmJlaW5zdHJhc3NlIDE4LTIwMQ0wCwYDVQQREwQ0MDU2MSEwHwYDVQQK
ExhVbml2ZXJzaXR5IExpYnJhcnkgQmFzZWwxEDAOBgNVBAMTB0R1bW15Q0EwHhcN
MjQwMzAzMTcxMTE1WhcNMzQwMzAxMTcxMTE1WjCBmDELMAkGA1UEBhMCQ0gxEzAR
BgNVBAgTCkJhc2VsIENpdHkxDjAMBgNVBAcTBUJhc2VsMSAwHgYDVQQJDBdTY2jD
tm5iZWluc3RyYXNzZSAxOC0yMDENMAsGA1UEERMENDA1NjEhMB8GA1UEChMYVW5p
dmVyc2l0eSBMaWJyYXJ5IEJhc2VsMRAwDgYDVQQDEwdEdW1teUNBMHYwEAYHKoZI
zj0CAQYFK4EEACIDYgAErHxZYoHwHzTqRg14Ve9/APs/D+sMSKDTpPTZYFocZedF
VGJEkeaCqQvsCY5G9WaHXI7jZtewKo/bHM/WcmXZB+cZNmJn/IyBHJAYh5xN5WBY
vUPJfRfQosSFr8SDE4MPo2EwXzAOBgNVHQ8BAf8EBAMCAoQwHQYDVR0lBBYwFAYI
KwYBBQUHAwIGCCsGAQUFBwMBMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFH+I
PuzNyAOrQ+rMTtywGqm3Z5ARMAoGCCqGSM49BAMDA2kAMGYCMQDJNau3j1v1FQHQ
n7kn+gEATGOm+9fBsgUCGXmKvLZPIJI3NI2URLmlmASdEIrg/N4CMQCNQio9BHom
JYLotIXmdUEmKuXZeKoc0eR1jA7kWdJNOvEpE73mx/zutDeNl3hRVP0=
-----END CERTIFICATE-----
"""]
usesystempool = false


[vfs.test]
name = "test"
type = "remote"
[vfs.test.remote]
address = "https://localhost:8762"
basedir = ""
[vfs.test.remote.clienttls]
type = "dev"
interval = "1h"

[vfs.tests3]
name = "tests3"
type = "remote"
[vfs.tests3.remote]
address = "https://localhost:8762"
basedir = ""
[vfs.tests3.remote.clienttls]
type = "dev"
interval = "1h"

[vfs.testcache]
name = "testcache"
type = "remote"
[vfs.testcache.remote]
address = "https://localhost:8762"
basedir = ""
[vfs.testcache.remote.clienttls]
type = "dev"
interval = "1h"

[log]
level = "debug"

[log.stash]
#logstash_host="sb-uwf4.swissbib.unibas.ch"
logstashhost="localhost"
logstashport=5046
logstashtracelevel="ERROR"
namespace="mediaserverpg"
dataset=""
#dataset="logs-mediaserver"
[log.stash.tls]
type="file"
ca=["certs/ca.crt"]
interval="1h"
[log.stash.tls.file]
cert="certs/ub-log.ub.unibas.ch.cert.pem"
key="certs/ub-log.ub.unibas.ch.key.pem"
