#localaddr = ":7685"
localaddr = ":0"
#domains = ["ubmedia", "mediathek"]
domains = ["ubmedia"]
instance = "ubimage"
resolveraddr = "127.0.0.1:7777"
resolvertimeout = "10m"
resolvernotfoundtimeout = "10s"
dbconn = "%%DATABASE_URL%%"
concurrency = 3

[server]
type = "minivault"
initialtimeout = "1h"
[server.minivault]
baseurl = "https://localhost:8759/api/v1"
parenttoken = "pa.2dd5c794e8b134bb.56011f6d9807a45d" #pa.2dc483e73851c137.15d94e61e0b377f1
tokentype = "server_cert"
tokenpolicies = ["instance_ubimage.mediaserveraction"]
tokeninterval = "48h"
tokenttl = "96h"
certtype = "server_cert"
dnss = ["instance_ubimage.mediaserverproto.Action"]
uris = []
ips = []
certinterval = "24h"
certttl = "48h"
ca = ["certs/minivault.ca.pem"]
usesystempool = false

[client]
type = "minivault"
initialtimeout = "1h"
[client.minivault]
baseurl = "https://localhost:8759/api/v1"
parenttoken = "pa.2dd5c794e8b134bb.56011f6d9807a45d" #pa.2dc483e73851c137.15d94e61e0b377f1
tokentype = "client_cert"
tokenpolicies = ["instance_ubimage.mediaserveraction"]
tokeninterval = "48h"
tokenttl = "96h"
certtype = "client_cert"
dnss = []
uris = [
    "grpc:miniresolverproto.MiniResolver",
    "grpc:ubmedia.mediaserverproto.Database",
    "grpc:mediathek.mediaserverproto.Database",
    "grpc:ubmedia.mediaserverproto.ActionDispatcher",
    "grpc:mediathek.mediaserverproto.ActionDispatcher"]
ips = []
certinterval = "24h"
certttl = "48h"
ca = ["certs/minivault.ca.pem"]
usesystempool = false

[vfs.test]
name = "test"
type = "remote"
[vfs.test.remote]
address = "https://localhost:8762"
basedir = ""
[vfs.test.remote.clienttls]
type = "dev"
interval = "1h"

[vfs.tests3]
name = "tests3"
type = "remote"
[vfs.tests3.remote]
address = "https://localhost:8762"
basedir = ""
[vfs.tests3.remote.clienttls]
type = "dev"
interval = "1h"

[vfs.testcache]
name = "testcache"
type = "remote"
[vfs.testcache.remote]
address = "https://localhost:8762"
basedir = ""
[vfs.testcache.remote.clienttls]
type = "dev"
interval = "1h"

[log]
level = "debug"

[log.stash]
#logstash_host="sb-uwf4.swissbib.unibas.ch"
logstashhost="localhost"
logstashport=5046
logstashtracelevel="ERROR"
namespace="mediaserverimage"
dataset=""
#dataset="logs-mediaserver"
[log.stash.tls]
type="file"
ca=["certs/ca.crt"]
interval="1h"
[log.stash.tls.file]
cert="certs/ub-log.ub.unibas.ch.cert.pem"
key="certs/ub-log.ub.unibas.ch.key.pem"
